### ISSUE TITLE
workless example for routing with custom server

### ISSUE THREAD

**Issue by foi** [onyxframework/docs#9]
Hi, Vlad! Awesome framework, but i have some issues:

crystal: 0.30.0

shards.lock
```
version: 1.0
shards:
  callbacks:
    github: vladfaust/callbacks.cr
    version: 0.2.0

  dotenv:
    github: gdotdesign/cr-dotenv
    version: 0.1.0

  exception_page:
    github: crystal-loot/exception_page
    version: 0.1.2

  http-params-serializable:
    github: vladfaust/http-params-serializable
    version: 0.4.0

  kilt:
    github: jeromegn/kilt
    version: 0.4.0

  onyx:
    github: onyxframework/onyx
    version: 0.6.1

  onyx-http:
    github: onyxframework/http
    version: 0.9.0

  radix:
    github: luislavena/radix
    version: 0.3.9

  time_format:
    github: vladfaust/time_format.cr
    version: 0.1.1

```
Example from here https://docs.onyxframework.org/http/advanced/custom-server.html#routing

```
require "onyx-http"

logger = Onyx::HTTP::Logger.new
request_id = Onyx::HTTP::RequestID.new
response_time = Onyx::HTTP::ResponseTime.new

router = Onyx::HTTP::Router.new do
  get "/" do |env|
    env.response << "Hello Onyx"
  end

  post "/echo" do |env|
    env.response << env.request.body.try &.gets_to_end
  end
end

server = Onyx::HTTP::Server.new(response_time, request_id, logger, router)

server.bind_tcp(5000)
server.listen
```

I have `Error: undefined constant Onyx::HTTP::Logger` and if comment this line have error in next line `Error: undefined constant Onyx::HTTP::RequestID`  and so on
